//var myObj=null;
//console.log(myObj);
//var a=new Array("cat","dog",3,true);
//console.log(a[1]);
var myObj= { };
console.log(myObj);
myObj.prop='hi';
console.log(myObj);
myObj.prop2=123;
console.log(myObj);
console.log('1st say'+myObj.prop);